<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tc3ProjectTools.Abstractions\Tc3ProjectTools.Abstractions.csproj" />
    <ProjectReference Include="..\Tc3ProjectTools.Runtime\Tc3ProjectTools.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fluent.Ribbon" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
