<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tc3ProjectTools.Runtime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tc3ProjectTools.Abstractions\Tc3ProjectTools.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
